import './globals.css';
import { Inter } from 'next/font/google';
import { SessionProvider } from 'next-auth/react';
import { getServerSession } from 'next-auth';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Login-system',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession({});

  return (
    <html lang="en">
      <body className={inter.className}>
        Ola {session?.user?.name}
         children
        {/* <SessionProvider session={session}>{children}</SessionProvider> */}
      </body>
    </html>
  );
}
